import Image from "next/image";
import "./globals.css";
import { Lexend } from "next/font/google";
import Navbar from "./Components/Navbar";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Hounter",
  description:
    "Generated by create next app find the place to live your dreams easily here",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Image
          className="absolute -top-4 -left-4 -z-10"
          src="/Images/ColorBlur.png"
          width="750"
          height="550"
        />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
